### ISSUE TITLE
Error: Failed retrieving fkey from chat.

### ISSUE THREAD

**Issue by Shah-Nisarg** [SO-Close-Vote-Reviewers/UserScripts#106]
I had this error on one of the questions today. I had tried about four times to post the CV-PLS request, and all four resulted in the same error. 

Unfortunately I do not recall the status code, nor do I have that tab open - so I can't check for the error in the network tab.

As discussed in the room, possible solutions would be,

- Giving markdown text to the user so they can paste it manually in the room
- Logging the details in console and/or saving key details in localStorage for future access

**Comment by Shah-Nisarg** [comment]
**Script:** Close Vote Request Generator
**Issue type:** Bug
**Link to example post: https://stackoverflow.com/q/46500780/5894241** (The problem doesn't seem likely to be replicated though.)

**Comment by makyen** [comment]
For users, we can incorporate the code I wrote for the bookmarklet version, which either copies the request text to the clipboard or displays it for the user to copy, depending on the capabilities available in that browser. This will give them the request text which they can paste into SOCVR (or whichever room they are using).

For debugging, at a minimum, we can log the response received to the console. That would at least give people a bit more information to work with.

I'm unsure about the idea of keeping logs in localStorage/userscript storage. While we certainly can do so, we would need to implement pruning to limit the amount of data stored so we don't fill up storage (either localStorage, or userscript storage): localStorage, because we don't want to break SO; userscript storage due to an issue on Chrome/Tampermonkey which can cause the browser to hang for many seconds when storing large amounts of data to userscript storage.

**Comment by Shah-Nisarg** [comment]
Okay, let's go with logging to console, and giving a way to copy the markdown. Where do I find your code?

**Comment by makyen** [comment]
The bookmarklet version is in this repository as [SECloseVoteRequestGenerator-bookmarklet.js](https://github.com/SO-Close-Vote-Reviewers/UserScripts/blob/master/SECloseVoteRequestGenerator-bookmarklet.js).

**Comment by makyen** [comment]
Having gotten some sleep and thinking about this a bit fresher, I'm going to change my position on automatically copying the text to the clipboard. I believe automatically copying to the clipboard in this error case is the wrong choice from a UX point of view.

For just the process of posting the cv-pls request, it's certainly a bit more convenient for the user to have the text automatically on the clipboard. For the bookmarklet, that's a good thing, as it's the normal and expected operation of the bookmarklet. It's what it does. The user expects the clipboard to be used to do this.

However, for the userscript, what we're discussing is what happens in an uncommon, error situation. The user is expecting the request to be automatically sent. They are *not* expecting to have the clipboard clobbered with new content. What if the user already has important information on the clipboard which they need and have no other copy of? If we automatically copy the request text to the clipboard, they would unexpectedly loose that information. With automatic copying to the clipboard upon error, the user needs to think about the possibility that the current contents of the clipboard might be randomly lost any time they try to send a cv-pls. The first time this happens, it will be quite unexpected. Subsequently, the user will have to keep in mind the potential for the clipboard to be clobbered.

Generally, we should not do things which, from the user's perspective, could be viewed as unexpectedly destroying data (the current clipboard content).

Thus, for this error condition, I think it's reasonable for us to display the request text and select that text, so it's easy for the user to copy it to the clipboard themselves, but not to automatically copy it to the clipboard. If we desire, we could include a button in the notification which copies the text to the clipboard, but I don't think we should do so automatically.

**Comment by Shah-Nisarg** [comment]
Good points! I will try and get a button in there for "Click to copy".

One question, do I close this pull request, and create a new one? Or, is there something that let's me *append* to the current PR?

**Comment by makyen** [comment]
Any commit you make (and push to GitHub) to the branch which you used for the PR will automatically be added to the PR. There's no way to avoid that happening. If you want commits to *not* be added to the PR, then you need to commit to a different branch, or not push to GitHub.

As to closing the PR and creating a new one, you're welcome to do it either way. If you want to *discard* your current changes, then it's best to close and open a new PR using a different branch. 

If you're building upon your current changes (i.e. adding commits), then you can either close the PR until your changes are ready and then re-open it, or leave the PR open until your changes are ready. Which of those two to do really depends on how much time you expect to need to take for any additional changes. Unless the changes are relatively quick, closing and reopening is probably cleaner, as it indicates you're not actually wanting it to be merged in it's current state.
