### ISSUE TITLE
Magic Editor: Cannot use backspace to delete whitespace part of a code block if it is selected

### ISSUE THREAD

**Issue by ferrybig** [SO-Close-Vote-Reviewers/UserScripts#109]
Based on my deleted MSO question: https://meta.stackoverflow.com/questions/358761/cannot-use-backspace-to-delete-whitespace-part-of-a-code-block-if-it-is-selected

> When selecting the newline + intention only, and then pressing backspace, something happens inside the SO editor, making it unable to actually delete the text.
> 
> Steps to reproduce:
> 
> 1. Code the code block to the answer section on the page (or press edit)
> 2. Start your selection from the end of `<tit` line
> 3. End your selection just before `le>`
> 4. Press backspace, as you are trying to "fix" the code
> 5. Expect that the unneeded newline is deleted
> 6. Observe the newline is still there, and your selection cleared
> 7. ???
> 
> I expect when I select from the enter after a line to the next word, that when I press backspace, the full block is deleted, however nothing happens.
> 
> Example, because this bug is hard to explain:
> 
> >! [![Bug that shows when pressing backspace after selecting whitespace only][1]][1]
> 
> 
> Try it out here:
> 
>     <html>
>         <head>
>              <tit
>              le>test</title>
>         </head>
>     </html>

After discussing in the comments on Meta SO, it seemed like this bug was caused by something inside the Magic Editor

[1]: https://i.stack.imgur.com/Hmksi.gif

**Comment by surajrao** [comment]
There seems to be a workaround which I tried to explain in the comment section in your question. Below is the recording.
![][1]

When using magic editor I used <kbd>Option</kbd> + <kbd>Delete</kbd> to remove selected content. In windows it could be Alt + Backspace/Delete
[1]: http://g.recordit.co/1Sjp00Oudu.gif

**Comment by makyen** [comment]
On Windows I can duplicate this using <kbd>Backspace</kbd>. A (Windows) workaround is to just use the <kbd>Delete</kbd> key instead.

**Comment by makyen** [comment]
Notes:
Our Magic™Editor fork gets the code for this functionality from [Better handling of indentation and the TAB key when editing posts](https://stackapps.com/questions/3247/better-handling-of-indentation-and-the-tab-key-when-editing-posts). Unfortunately, [the repository for that project](https://bitbucket.org/balpha/se-tab-edting/overview) appears to be unmaintained (last update 2012-03-27). However, the owner did [interact with a pull request on 2016-03-17](https://bitbucket.org/balpha/se-tab-edting/pull-requests/2/fix-bug-with-shift-tab-behaviour-which/diff). The owner is still around (i.e. [active on Stack Exchange](https://stackexchange.com/users/40051/balpha?tab=activity) & an SO employee). There are three pull requests pending, including one from 2015 that addresses this issue (or at least something quite close). The repository is hosted on bitbucket.org, which does not support filing issues.

The [other PR which we might be interested in incorporating](https://bitbucket.org/balpha/se-tab-edting/pull-requests/2/fix-bug-with-shift-tab-behaviour-which/diff) would not be compatible with IE (if that's something we are attempting to maintain), but could be easily changed to be compatible with IE.

The most recent PR on that project only affects things specific to that project being a separate userscript.

**Comment by mogsdad** [comment]
Balpha's script intended to treat backspace as a tab alignment, when the line began with just whitespace. However, it didn't specifically handle selections properly. I think it's best if we go with native behavior for backspace when there is a selection, otherwise preserving the tab alignment behavior.
