### ISSUE TITLE
cv-pls menu remains visible when abandoned

### ISSUE THREAD

**Issue by mogsdad** [SO-Close-Vote-Reviewers/UserScripts#11]
Simple reproduction:

 1. Click <kbd>cv-pls</kbd> action when viewing a question. Observe menu pop-up.
 2. Abandon the action, by doing something else. For example, click <kbd>share</kbd> action. Observe that the pop-up menu remains visible.

![screenshot](https://cloud.githubusercontent.com/assets/1707731/9291840/f3fb6f0e-43a4-11e5-9064-4ed1c8a8ecf0.png)

I first noticed this by choosing to "Send Request", then hitting <kbd>cancel</kbd> in the resulting dialog.

**Comment by mogsdad** [comment]
Can still reproduce the reported problem, although the behavior for <kbd>cancel</kbd> is fixed.

**Comment by Tiny-Giant** [comment]
It should be fixed in this script. 

https://gist.github.com/Tiny-Giant/0694197d7bca91196dd8/raw/8f3167c21c4cc75d44fddfdc4e76642681f4c1a4/SECloseVoteRequestGenerator.user.js

**Comment by mogsdad** [comment]
That appears to have done the trick. Validated that the pop-up menu cleared when user:

 - clicked any other answer action (<kbd>share</kbd>, <kbd>edit</kbd>, <kbd>close</kbd>, or <kbd>flag</kbd>).
 - clicked <kbd>add a comment</kbd>, or <kbd>help</kbd> (if the comment dialog was open).
 - and other ad-hoc testing of other actions available on the page. 

Defect has been addressed.
