### ISSUE TITLE
Move help out of comments and into readme

### ISSUE THREAD

**Issue by durron597** [SO-Close-Vote-Reviewers/UserScripts#12]
Could you move the help from the SOCloseVote script into the README.md from the comments in the user script?

Thanks!

**Comment by Tiny-Giant** [comment]
@gunr2171  Would it be alright if I appended this to the main README.md?

**Comment by gunr2171** [comment]
Let's add headers to the main Readme file, one for each script.

**Comment by gunr2171** [comment]
Made a PR, thoughts?

**Comment by Tiny-Giant** [comment]
The PR looks good, and I think a section for each UserScript would make sense.
