### ISSUE TITLE
CV request generator shows last editors name instead of original author.

### ISSUE THREAD

**Issue by surajrao** [SO-Close-Vote-Reviewers/UserScripts#122]
As the title suggests: 

The request shows the user account which had last edited the question requested to be cv'ed.

Example 

https://chat.stackoverflow.com/transcript/message/41485157#41485157

![screen shot 2018-03-05 at 11 24 53 am](https://user-images.githubusercontent.com/5566582/36959417-e2b7e04a-2067-11e8-98c7-f42ba7402b73.png)

Edit revision:

https://stackoverflow.com/posts/49102913/revisions

![screen shot 2018-03-05 at 11 25 40 am](https://user-images.githubusercontent.com/5566582/36959431-f9b9063e-2067-11e8-850a-0fb3b8cd27ed.png)

Screenshots added in case of post deletion.

**Comment by makyen** [comment]
This is almost certainly the result of Stack Exchange's recent restructuring of the HTML for this area of the page. I'll take a look at it.
