### ISSUE TITLE
Remove dependency on i.stack.imgur.com, so icon will show when that domain is blocked

### ISSUE THREAD

**Issue by GrumpyCrouton** [SO-Close-Vote-Reviewers/UserScripts#124]
I thought that my Magic Editor was just not working (on Chrome), because the icon was not showing. I haven't had the icon in a few days, but I was just hovering around my toolbar and noticed I could still click the button, but the icon does not show.

I am on version 1.6.0.2.

![tiny](https://user-images.githubusercontent.com/12193403/37001655-cfc3da3c-208c-11e8-8fec-eb2f59d89f39.png)

**Comment by makyen** [comment]
I'm not able to easily duplicate this issue. I'm going to need some more information. Could you tell me: 

* Your OS
* The userscript manager you're using.
* A URL on which you're having the problem
* Anything you're doing in the page (e.g. is it when you click "edit" on a post (which one))
* Is it appearing in the "Your Answer" box?
* Do you have any other userscripts running? If so, have you tried turning them off to check for interference (I usually use a binary search, after taking a screenshot to remember which ones I already have disabled)?

I did see something like this when working on the previous version, but that was resolved with CSS/style changes. I have not seen this once that was resolved (in 1.6.0.0).

**Comment by GrumpyCrouton** [comment]
- Windows 10
- Tampermonkey
- All stack exchange sites
- Editing a post, posting a question, posting an answer. Basically everywhere the icon _should_ show.
- No.
- I have several running, but disabling ALL of them except magic editor does not resolve the issue.

**Comment by GrumpyCrouton** [comment]
Any update? I still have this issue.

**Comment by GrumpyCrouton** [comment]
I'm using Tampermonkey on Google Chrome version 65.0.3325.181 and version v1.6.0.2 of Magic Editor.

**Comment by GrumpyCrouton** [comment]
I think I've figured out what the issue is by viewing the icon in Inspect Element. I've noticed that the image is hosted on i.stack.imgur.com which unfortunately has been blocked on the network I am currently using. Has this image always been hostetd here?

**Comment by makyen** [comment]
Blocking that domain would certainly cause the problem you are seeing.

Yes, it has been that way for the last 2 years. Prior to that it was in the `i.imgur.com` domain for more than a year prior to that (i.e. from almost 4 years ago to 2 years ago).

**Comment by makyen** [comment]
FYI: I've converted the icon to SVG and included it within the script.  This will be fixed in the next version I push.
