### ISSUE TITLE
Magic Editor: A vs An when preceded by the word Column

### ISSUE THREAD

**Issue by K-Davis1** [SO-Close-Vote-Reviewers/UserScripts#128]
Magic Editor is currently replacing the letter "A" with "An" when it's used after the word "Column".

Take the following example:

> Column A contains a string

is converted to:

> Column An contains a string

**Comment by makyen** [comment]
Please provide an example post/revision where this is happening.

**Comment by K-Davis1** [comment]
You can just copy my example into a post and use Magic Editor on it ;-)

But if I stumble upon another one I will certainly post it.
