### ISSUE TITLE
Magic Editor: Replacing "regex" with "RegEx" is misdirected

### ISSUE THREAD

**Issue by tripleee** [SO-Close-Vote-Reviewers/UserScripts#138]
It looks like the magic editor will replace "regex" with "RegEx" and claim it proper-cased a trademark.

This is incorrect or at least misleading, and often not an improvement.

Currently the problematic code is around line 363.

https://github.com/SO-Close-Vote-Reviewers/UserScripts/blob/master/Magic%E2%84%A2Editor.user.js#L363

If you agree with this change I'll be happy to chuck a PR.

**Comment by makyen** [comment]
Is it reasonable to do this substitution on questions that are tagged with JavaScript, or associated tags?
