### ISSUE TITLE
Add support to fix dashes with Magic™Editor

### ISSUE THREAD

**Issue by BaumMitAugen** [SO-Close-Vote-Reviewers/UserScripts#141]
Could the script replace `--` and `---`  in non-code areas with `&ndash;` and `&mdash;` respectively?

**Comment by K-Davis1** [comment]
Does `- - -` (added spaces since iPhone autocorrects to —) do the equivalent of `<del>` in posts like they do on the chat servers?

**Comment by BaumMitAugen** [comment]
No, it does not.

**Comment by makyen** [comment]
There are a couple of Markdown conflicts that would need to be watched out for.

h2 headers
--

and horizontal rules

---

However, those both require that the `/--+/` be the first characters on the line other than whitespace, which could be avoided.

Do you have some examples of where this would be helpful? I don't recall ever seeing a post where this would be something I'd want done. OTOH, those are two characters that live in my permanent clipboard, so using them isn't something I'd take much notice of. I think that I've encountered occasions where this would be detrimental (mostly in things that probably should be code). However, my memory of those possible times is vague.

**Comment by makyen** [comment]
The [first example you gave](https://stackoverflow.com/posts/12476379/revisions) shows changing `--` to `&mdash;`. From your first comment here, I was under the impression that you wanted `--` to be changed to `&ndash;`. What should MagicEditor be doing?

**Comment by BaumMitAugen** [comment]
> The [first example you gave](https://stackoverflow.com/posts/12476379/revisions) shows changing `--` to `&mdash;`. From your first comment here, I was under the impression that you wanted `--` to be changed to `&ndash;`. What should MagicEditor be doing?

In the  first example, I used `&mdash;` because there was no space around the dash; and from what I've seen, I've thought either `word&mdash;word` or `word &ndash; word` are the predominant styles in use.

I might be wrong about that though; and I would not pick a fight with someone who prefers `word&ndash;word` either. So to be explicit, it appears to me that mapping to `&mdash;` vs `&ndash;` in that case would be a matter of opinion; if you have a preference or are aware of accepted style guides calling for one or the other, I'd be happy with either choice.

Anyway, thank you for your time and your reply!

**Comment by makyen** [comment]
My experience with `&ndash;` and `&mdash` is primarily on Wikipedia. I really haven't participated much on Wikipedia for a couple of years, but what I recall was that their guidelines were that it was always to be one of `word&mdash;word` or `word &ndash; word`. Examples:
word&mdash;word
 or 
word &ndash; word
In other words, an `&ndash;` was always to be used if there were spaces separating it from the words, whereas an `&mdash;` was always to be used if there were no spaces.
