### ISSUE TITLE
Alert Box hasn't been encoded correctly

### ISSUE THREAD

**Issue by dippas** [SO-Close-Vote-Reviewers/UserScripts#166]
Hi, I noticed while voting to close an old question (typo reason), that the alert box has some HTML not properly encoded

![image](https://user-images.githubusercontent.com/10220287/59517487-391cf500-8eb3-11e9-8ccc-651008da10d7.png)

**Comment by makyen** [comment]
This should be resolved in version 1.8.8.0, which is now available.
