### ISSUE TITLE
CV-Request dialog truncated if question has no comments

### ISSUE THREAD

**Issue by jhgarrison** [SO-Close-Vote-Reviewers/UserScripts#170]
WIndows 10 Pro 64
CVRequest Generator 1.6.8
Firefox 68.0.2

If the question does not have comments, the dialogs displayed by the tool are truncated around the point where comments would begin.  If the post has comments, truncation does not seem to occur.

![socvr-01](https://user-images.githubusercontent.com/2840152/63994205-a3a00300-caa8-11e9-8cdb-7536532a2f82.png)
![socvr-02](https://user-images.githubusercontent.com/2840152/63994208-a69af380-caa8-11e9-86cc-ed4bd1999020.png)
![socvr-03](https://user-images.githubusercontent.com/2840152/63994213-a8fd4d80-caa8-11e9-8843-5cb2a5c67f76.png)

**Comment by jhgarrison** [comment]
Truncation happens whenever the dialog vertical size exceeds the comment space, as in:

![socvr-04](https://user-images.githubusercontent.com/2840152/63994533-c41c8d00-caa9-11e9-971f-67a2879da6ce.png)

**Comment by makyen** [comment]
Versions 1.6.9 (release) and 1.8.8.0 (alpha) have been pushed to GitHub. They should resolve this issue.
