### ISSUE TITLE
No cv-pls checkbox in Close question dialog after latest SO update

### ISSUE THREAD

**Issue by vkotovv** [SO-Close-Vote-Reviewers/UserScripts#183]
There is no cv-pls checkbox in Close question dialog after latest update on SO and SE. For example, see post about keyboard shortcuts - https://meta.stackexchange.com/questions/346451/changes-to-the-close-dialogue-have-broken-keyboard-shortcuts-for-closing-a-post

CV Request Generator 1.6.11

**Comment by makyen** [comment]
The alpha version, version 1.9.0.0 ([GitHub](//git.io/SOCVR-CVRG-MakNewVer)) ([install](//github.com/SO-Close-Vote-Reviewers/UserScripts/raw/CVRG-Mak-new-version/SECloseVoteRequestGenerator.user.js)), has been updated to resolve this. The "released" version has not yet been updated to resolve this problem.

**Comment by makyen** [comment]
Thanks for the report. It looks like this was resolved by switching the repository over to the 2.X version of the Request Generator. If it's still an issue, please post a new comment here, reopen this issue, or create a new issue.
