### ISSUE TITLE
Replace window.prompt and alter with something that doesn't block the browser input

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/UserScripts#19]
I use Chrome. I leave the chat room on one monitor and the post I'm working on the other.

Let's say I want to change the room I'm posting to.

1. Go to the post.
2. Hit `cv-pls` menu and choose "Set target room"
3. Go to the chat room and copy the url

Oh wait, I can't. `window.prompt` blocks user input to the entire browser until it's finished. Same with `alert`.

It's frustrating :(

Here's an example dialog box I whipped up real fast.

```
var postMenu = $('#question .postcell .post-menu');

var popupBox = $('<div class="popup" style="position: absolute; top: 399.5px; left: calc(50% - 416px); display: block;"></div>');
popupBox.append('<div class="popup-close"><a title="close this popup (or hit Esc)">×</a></div>');
popupBox.append('<h2>This is the popup window title!</h2>');

//add more things here

postMenu.append(popupBox);
```

If we can get this working, we can make the "request sent successfully" auto-disappear, so you don't have to spend a mouse click to make it go away.

**Comment by Tiny-Giant** [comment]
Sounds good, I'll implement this asap

**Comment by durron597** [comment]
As a workaround, you can just hit enter again (at least you can on Chrome).

**Comment by Tiny-Giant** [comment]
Alerts and prompts have been removed in favour of other methods, the only window dialog still used is for the update notification. Also, the new "alerts" use the StackExchange.notify functions, and any non-error notifications will auto-hide themselves.
