### ISSUE TITLE
Close Vote Request Generator no more working under Edge DEV Version 90.0.810.1

### ISSUE THREAD

**Issue by slear** [SO-Close-Vote-Reviewers/UserScripts#197]
In the latest version of the **Edge DEV (Chromium)**, the script seems to be no more working. The link under the question doesn't appear anymore. Not sure if it is related but the latest version of the browser has added a new 'feature' to hide the extensions in a dropdown menu tool instead of always showing them on the toolbar. I have moved the **Tampermonkey** extension under the menu tool but then noticed the missing link. However, now even restoring the TM icon on the toolbar doesn't make the link visible again. This happened also to another script, **"Advanced flagging"** from sobotics.org. It shows the same behavior. _@double-beep_ user resolved the problem in that script asking me to reinstall a previous version, so perhaps they have some clues on what's going on.

**Comment by slear** [comment]
@double-beep suggested to try the alpha version 1.10.2.0 and this one worked as before.

**Comment by makyen** [comment]
This was resolved by switching the repository over to the 2.X version of the userscript.
