### ISSUE TITLE
cv-pls generator: Why doesn't it have @updateURL and @downloadURL ?

### ISSUE THREAD

**Issue by iBug** [SO-Close-Vote-Reviewers/UserScripts#199]
Just two simple lines that makes keeping the script up-to-date easier:

<https://github.com/SO-Close-Vote-Reviewers/UserScripts/blob/CVRG-Mak-new-version/SECloseVoteRequestGenerator.user.js>

```js
// @updateURL      https://raw.githubusercontent.com/SO-Close-Vote-Reviewers/UserScripts/CVRG-Mak-new-version/SECloseVoteRequestGenerator.user.js
// @downloadURL    https://raw.githubusercontent.com/SO-Close-Vote-Reviewers/UserScripts/CVRG-Mak-new-version/SECloseVoteRequestGenerator.user.js
```

I'm curious why they aren't there. It took me quite some time to notice that my installed version has long been outdated.

**Comment by Tyler-H** [comment]
Ostensibly this was because the script was in Alpha. These were added by Makyen in the release of 2.0.0 which moved the script out of Alpha.
