### ISSUE TITLE
SOCVRG Use custom dialogs instead of alerts

### ISSUE THREAD

**Issue by mogsdad** [SO-Close-Vote-Reviewers/UserScripts#20]
Alerts are bad, Mkay? A stupid user (hi) might just click "Prevent this page from creating additional dialogs”, thereby rendering the tool useless.

It [is possible](http://stackoverflow.com/a/23697435) to check whether alerts are showing, to help stupid users (stop talking about me!) fix things.

**Comment by gunr2171** [comment]
Possible duplicate of #19

**Comment by mogsdad** [comment]
Yep, different reason, but a single changeset would address both.

**Comment by Tiny-Giant** [comment]
Yeah, working on it now.

**Comment by Tiny-Giant** [comment]
The current version no longer uses alerts or prompts, it will still use a confirm dialog for version updates, but otherwise not.
