### ISSUE TITLE
Opening the cv-pls menu after sending a request keeps the last reason filled in

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/UserScripts#22]
If you send a cv-pls request and don't refresh the page, the reason you used will still be filled in.

![](http://g.recordit.co/inNEVe5Mw2.gif)

I'm actually not sure if this is a good idea or a bug. It shows you that you already requested it (in case you double-request by accident).

**Comment by Tiny-Giant** [comment]
Yeah, I noticed this as well when I was building it. I decided to leave it in for the reason you mentioned, as well as you may want to send it to multiple chatrooms, so retyping the reason may be an inconvenience.. Still open to arguments for why it should be cleared, but for right now I'm going to leave it in.

**Comment by gunr2171** [comment]
I'm ok with leaving this as-is. We can reopen if we change our minds.
