### ISSUE TITLE
UI improvements when setting a new target room

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/UserScripts#23]
There are a [couple][1] changes I would suggest when setting a new target room.

1. The banner at the top doesn't stick around for long enough. There's no way I can read all that text by the time it goes away.

2. Let's change the banner text to show the name of the room rather than the url. Should be able to get the human-friendly name from the `/rooms/info/#` page.

3. After a new target room is set, the input elements are still visible. I think it should be collapsed back into the menu item once successfully changed.

4. Above the input box should read some text about what is currently set. Maybe something like
     > The current target room for (site name) posts is (name of chat room).

 [1]: https://xkcd.com/1070/

**Comment by Tiny-Giant** [comment]
Sounds good. I've been trying to figure out some good UX for this, thanks. Will put this in the next version.

**Comment by Tiny-Giant** [comment]
Fixed in Version 1.4.7
