### ISSUE TITLE
Hit boxes for menu items need to be taller

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/UserScripts#24]
It's sometimes really hard to click a menu item. The hitboxes are just too small compared to their container.

![image](https://cloud.githubusercontent.com/assets/8290105/9331449/a8d23950-458d-11e5-85dd-53fa5fceadc3.png)

The real killer is that the entire clickable region changes the cursor to a pointer, so the only indication that you are on the right part is the link changes color.

**Comment by Tiny-Giant** [comment]
Yeah, I've been meaning to fix this for a while. Will put this in the next version.

**Comment by Tiny-Giant** [comment]
Fixed in Version 1.4.7
