### ISSUE TITLE
If text goes off-screen on any input box you are unable to manually select it

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/UserScripts#26]
So this was a bit strange:

![](http://g.recordit.co/uzdXjdcq27.gif)

It seems that if the text from an input box goes off the side of the box, and you try to click and select text (like if you wanted to go to the end of the string to see what room is set), it will freak out and start inserting `javascript:void(0)` in the text.

I can still use the arrow keys, end key, and select + a, but I would still like to be able to select text on my own.

**Comment by Tiny-Giant** [comment]
Odd.... I'll take a look.

**Comment by Tiny-Giant** [comment]
Fixed in Version 1.4.7
