### ISSUE TITLE
If a post title has markdown characters it messes up posted chat messages

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/UserScripts#27]
I tested a cv-pls on this meta post: [Stop protecting [protect]][1].

[It didn't end well][2]:

![image](https://cloud.githubusercontent.com/assets/8290105/9331789/49e03f6c-458f-11e5-99d6-ee2a4e8a8b39.png)

We need to either escape those values or strip them out, depending on which is easier or possible.

[1]: http://meta.stackoverflow.com/questions/302679/stop-protecting-protect
[2]: http://chat.stackoverflow.com/transcript/message/25154536#25154536

**Comment by Unihedro** [comment]
`escapeMarkdown = e => e.replace(/[\\\[\]_*]/g, '\$1'/)`

**Comment by mogsdad** [comment]
We've observed that such messages don't always end up in Andy's room. I'd posted a reason containing `[tag:source]`, and it [got missed](http://chat.stackoverflow.com/transcript/message/25134910#25134910).

**Comment by Tiny-Giant** [comment]
@uni Thanks, I'll put that in the next version.

**Comment by Tiny-Giant** [comment]
Fixed in Version 1.4.7
