### ISSUE TITLE
Keystroke doesn't work if I take my fingers off Ctrl + Shift too quickly

### ISSUE THREAD

**Issue by durron597** [SO-Close-Vote-Reviewers/UserScripts#28]
Typically when I press the keystroke, I do the following:

1. Press <kbd>Ctrl</kbd> with my pinky
2. Press <kbd>Shift</kbd> with my ring finger
3. Press <kbd>a</kbd> with my middle finger
4. Lift my pinky
5. Lift my ring
6. Lift my middle finger

If I do this too quickly, the cv-pls dialog does not appear. However, if instead I:

4. Lift my middle finger

It seems to work. This bug can be reproduced always on Chrome 44.0.2403.155 m, with script version 1.4.6.

**Comment by Tiny-Giant** [comment]
Can reproduce, should be fixed in the next version.

**Comment by Tiny-Giant** [comment]
Fixed in Version 1.4.7
