### ISSUE TITLE
Add the ability to customize the keystroke

### ISSUE THREAD

**Issue by durron597** [SO-Close-Vote-Reviewers/UserScripts#30]
Personally, I like <kbd>Ctrl+Shift+a</kbd>, but others may not, especially in browsers not Chrome.

Can we have the ability to customize it in the cv-plz menu?

**Comment by durron597** [comment]
Easy link to the relevant spot:

https://github.com/SO-Close-Vote-Reviewers/UserScripts/blob/master/SECloseVoteRequestGenerator.user.js#L372

**Comment by Tiny-Giant** [comment]
Yeah, I'll mock something up later today and create a pull request.
