### ISSUE TITLE
Do not post 'cv-pls' in room meetings.

### ISSUE THREAD

**Issue by AlexanderStopher** [SO-Close-Vote-Reviewers/UserScripts#36]
As the title states, the 'cv-pls' button should be locked when a scheduled room meeting is happening. This stops the meeting from being interrupted (and the requests from being sent to the trash), so therefore effectively improves the focus of the meeting.

**Comment by Tyler-H** [comment]
This wouldn't do anything against manual cv-pls requests in the room, though, would it?

**Comment by gunr2171** [comment]
There are two other options for room meetings:

1. Make the chat room a gallery. Only selected people can talk. However, this messes up the room's permissions and we need to fix that afterwards.
2. Make a separate chat room just for meetings which is open.

**Comment by Tiny-Giant** [comment]
I'm in favor of option 2.

**Comment by NathanOliver1** [comment]
Don't rooms go away if they are not used after so long?  I am just worried about losing the history.

**Comment by AlexanderStopher** [comment]
Good point, isn't it something like 7 days?

**Comment by Tyler-H** [comment]
Whoever captains a room meeting can be responsible for putting the transcript in a non-expiring pastebin or gist here

**Comment by Tiny-Giant** [comment]
Only if they have lower than a certain number of entries. I don't think we would lose it with the amount of talking we do in room meetings.

**Comment by Tyler-H** [comment]
I'm pretty sure any room will be removed after a certain period of inactivity, regardless of entries or members

**Comment by NathanOliver1** [comment]
I was able to find this: http://meta.stackexchange.com/a/163963/291223

**Comment by Tiny-Giant** [comment]
According to that it will not be deleted based on our usage. That's not to say there isn't some other criteria for room deletion.

**Comment by NathanOliver1** [comment]
Well if we just have a room for meetings it will get deleted.  A room will get deleted automatically if it is inactive for 7 days.

**Comment by Tiny-Giant** [comment]
Ok, well he have Madara's word that they will unfreeze the room when needed for us. We can start off that way, then we can burn any other bridges as we cross them

**Comment by Unihedro** [comment]
If your meetings are distracted from so easily then you probably have a bigger problem to worry about. This feature request is dubious.

**Comment by ArcticEcho** [comment]
To clear up this confusion room deletion.

Rooms with <15 messages by only 2 users (or less):

 * *Deleted* after 7 days of inactivity.

Rooms with >15 messages by >2 users:

 * *Frozen* after 14 days of inactivity.

So, a room for meetings wouldn't actually get deleted.

**Comment by NathanOliver1** [comment]
Well I am good with that.  As long as the mods are okay with unfreezing the room when we need it.
