### ISSUE TITLE
Edit/Update Removal can eliminate too much white space.

### ISSUE THREAD

**Issue by mogsdad** [SO-Close-Vote-Reviewers/UserScripts#46]
**Script:** Magic™ Editor
**Issue type:** Bug
**Link to example post:** (where can the problem be reliably replicated?)

This:

```
Generally i need to pick up `authData` and `RequestData` elements to the one level up (or to delete `processRequestRequest` element).


**UPDATE**

> Spring WS offers "only" contract-first, starting from an XSD Schema
```

...gets changed to this:

```
Generally I need to pick up `authData` and `RequestData` elements to the one level up (or to delete `processRequestRequest` element).> Spring WS offers "only" contract-first, starting from an XSD Schema
```

...it should be this:

```
Generally I need to pick up `authData` and `RequestData` elements to the one level up (or to delete `processRequestRequest` element).

> Spring WS offers "only" contract-first, starting from an XSD Schema
```

...but the white space between the Block-quote and the preceding sentence has been removed.

Observed in [this edit](http://stackoverflow.com/posts/34737715/edit/78eb68dd-4149-4bf5-b4e6-c754b2540949), for example.

With `App.globals.showRules = true;`, isolated the problem to an apparent interaction between two rules, `editupdate` and `blanklines`, shown below. Debug info didn't show any unexpected replacement, so perhaps there is a third player? (Placeholder logic, maybe?)

With either rule disabled, there's no problem (but that the rule isn't doing its job).

```
        editupdate: {
            // https://regex101.com/r/tT2pK6/9
            expr: /([-_*]+[\t ]*\b(edit|update)\b([\t ]*#?[0-9]+)?[\t ]*:*[\t ]*[-_*]+:*|[\t ]*\b(edit|update)\b([\t ]*#?[0-9]+)?\s*:+[\t ]*)/gi,
            replacement: "",
            reason: App.consts.reasons.noise
        },

...
        blanklines: {  // https://regex101.com/r/eA5hA2/2
            expr: /^(?: *[\n\r\f])+|(?: *[\n\r\f])+$|((?: *[\n\r\f]){2})(?:(?: *[\n\r\f]))+/g,
            replacement: "$1",
            reason: App.consts.reasons.layout
        },
```

This might be related to issue #39 , in that the placeholders / block replacement logic could be involved.

(Migrated from [old repository #115](https://github.com/Tiny-Giant/Stack-Exchange-Editor-Toolkit/issues/115).)

**Comment by makyen** [comment]
This appears to have been previously resolved. The edits provided as test cases no longer appear to have the problem.
