### ISSUE TITLE
Add question tag(s) to cv-pls request

### ISSUE THREAD

**Issue by jdd-software** [SO-Close-Vote-Reviewers/UserScripts#52]
The question tag (most relevant or all) should be added as es. [java] not [tag:java] to the cv-pls request, before or after the title.

 **Reasons:**
1) On duplicate request, hammer in SOCVR chat can immediately identify if he can hammer.
2) User in chat and when [searching](http://chat.stackoverflow.com/search?q=tagged%2Fcv-pls&Room=41570&page=1&pagesize=50&sort=newest) on previous requests can filter on specific tag.

**Comment by makyen** [comment]
This was implemented some time ago.
