### ISSUE TITLE
Duplicate requests showing wrong author name

### ISSUE THREAD

**Issue by mogsdad** [SO-Close-Vote-Reviewers/UserScripts#59]
**Script:** Close Vote Request Generator
**Issue type:** Bug
**Link to example post:** http://chat.stackoverflow.com/transcript/41570?m=29479725#29479725

Instead of showing the name of the post's author, the script populates the name of the author of the dupe-target question.

**Comment by makyen** [comment]
To the best of my knowledge, this was resolved quite some time ago. If it is still a problem, please reopen or create a new issue.
