### ISSUE TITLE
Constant nags about cross-origin resources from Tampermonkey

### ISSUE THREAD

**Issue by AStopher** [SO-Close-Vote-Reviewers/UserScripts#65]
I'm constantly nagged about cross-origin resource requests with the SOCVR Request Generator script, whenever I do anything on the page *besides* from loading it, for example:

- Refreshing;
- Voting;
- Flagging;
- Commenting

Please could this be fixed?
I've now set all requests to 'ignore', but now I'm experiencing an `Failed retrieving fkey from chat` notification message where the 'Sent cv-pls request' message should be.

![image](https://cloud.githubusercontent.com/assets/10122241/14245504/cb56954e-fa59-11e5-931b-fee5fd20f3fa.png)

**Comment by jdd-software** [comment]
I experience similar issue (after installing latest chrome on new pc). I get same window but when loading question (pushing Always allow domain), the cv pls link is visible but if I try to send "Failed retrieving fkey from chat",  The script also gets uninstalled from tamper monkey after this.

**Comment by AStopher** [comment]
There's a missing semicolon at line 255, and at 237 removing `http:` makes the cv-pls request go through.

However I am still recieving the 'cross-origin resource' message.

**Comment by AStopher** [comment]
I also note that adding `// @connect        /(https?:\/\/chat\.(meta\.)?stack(overflow|exchange)\.com)\/rooms\/(.*)\/.*/` to the header (if that's what it's called...) of the script fixes the 'cross-origin resource' issue, but the 'fkey' issue is still present.

**Comment by Tiny-Giant** [comment]
I'll take a look at it when I get a chance, been really busy at work recently.

**Comment by kevin-brown** [comment]
The "cross-origin resource" issue appears to be happening because we're requesting the version number (which is on rawgit.com), but we aren't requesting any permissions for access to that domain in the userscript. Adding a `@connect` line for that page on rawgit.com should fix that issue.

**Comment by Tiny-Giant** [comment]
That must have been added in the most recent version of tampermonkey. We should also be requesting access to chat.stackexchange.com as well then.

**Comment by AStopher** [comment]
Are there any updates to this?

**Comment by rschrieken** [comment]
@AStopher  I pushed a new version that hopefully fixes this issue
