### ISSUE TITLE
BotCommands Script is outdated

### ISSUE THREAD

**Issue by Jacob-Gray** [SO-Close-Vote-Reviewers/UserScripts#75]
There is at least one outdated command in the [BotCommands UserScript](https://github.com/SO-Close-Vote-Reviewers/UserScripts/blob/master/BotCommands.user.js)

On [line #54](https://github.com/SO-Close-Vote-Reviewers/UserScripts/blob/master/BotCommands.user.js#L54), it lists `room effectiveness` as a command, which apparently doesn't work anymore.

**Comment by mogsdad** [comment]
https://github.com/SO-Close-Vote-Reviewers/UserScripts/commit/d51850b50b132250eca68524b66f32646a690058
