### ISSUE TITLE
The CV request generator doesn't work with keyboard shortcuts

### ISSUE THREAD

**Issue by NobodyNada** [SO-Close-Vote-Reviewers/UserScripts#82]
I often use the keyboard shortcuts to quickly cast close votes, but the "Send CV request" check box does not appear when I use them.

**Comment by makyen** [comment]
Thanks for the report. This was resolved by switching the repository over to the 2.X version of the Request Generator. If it's still an issue, please post a new comment here, reopen this issue, or create a new issue.
