### ISSUE TITLE
CV request generator inactive after editing

### ISSUE THREAD

**Issue by tripleee** [SO-Close-Vote-Reviewers/UserScripts#83]
I don't yet have a solid test case but just now, after I edited a question and then tried to cast a close vote, I did not see a "send cv-pls request" checkbox in the close reason dialog.  Reloading the page by clicking the question title and then reopening the close reason dialog brought it back.

**Comment by tripleee** [comment]
Unable to repro; I guess the URL I had to the question was wrong (maybe it pointed to a comment?)

**Comment by vkotovv** [comment]
See #139 for steps to reproduce
