### ISSUE TITLE
Unclosed Request Review Script dies on reports from deleted users

### ISSUE THREAD

**Issue by paulroub** [SO-Close-Vote-Reviewers/UserScripts#95]
The request at https://chat.stackoverflow.com/transcript/message/37904956#37904956 is from user8234819, with no link. `checkDone()` looks for the reporting-user's `<a>` tag and blindly tests its `href` attribute. Since there is no link here, we fail with 

> Uncaught TypeError: Cannot read property 'href' of null  
>    at Object.funcs.checkDone (eval at E_c (:3:221), <anonymous>:82:83)  
>    at XMLHttpRequest.xhr.addEventListener.event (eval at E_c (:3:221), <anonymous>:218:27)

**Comment by rschrieken** [comment]
merged the PR, thanks!
