### ISSUE TITLE
Magic™ seems to magically remove code-blocks if they follow a "Thank you!"

### ISSUE THREAD

**Issue by Vogel612** [SO-Close-Vote-Reviewers/UserScripts#98]
Observed when magicking [this exact revision](https://codereview.stackexchange.com/revisions/172959/1). 

Before:
![Before: There is a Thank You! with a codeblock](https://user-images.githubusercontent.com/7288995/29313582-25f6f6d0-81bb-11e7-972a-54f387187134.png)

After:
![After: the code-block placeholder has been removed as username signature](https://user-images.githubusercontent.com/7288995/29313583-25f8bcf4-81bb-11e7-8b87-065cdb6e2f01.png)

Apparently the codeblock placeholder was considered to be a username and got removed. That shouldn't happen

**Comment by makyen** [comment]
Resolved with [pull request #102](https://github.com/SO-Close-Vote-Reviewers/UserScripts/commit/2f390e692d94e5330f6d6d27018623ad7a619e3a).
